version: '3'

services:
  web:
    build: .
    volumes:
      - ./docroot:/var/www/html/dcg/docroot
      - ./docker-utils/php/config/xdebug.ini:/etc/php/7.2/fpm/conf.d/xdebug.ini
      - ./docker-utils/php/config/xdebug.ini:/etc/php/7.2/cli/conf.d/xdebug.ini
      - ./docker-utils/php/config/xdebug.ini:/etc/php/7.2/apache2/conf.d/xdebug.ini
    depends_on:
      - db
    container_name: dcg_web
  db:
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dcg
      MYSQL_USER: dev
      MYSQL_PASSWORD: changeme
    container_name: dcg_db

  proxy:
    image: alm-nginx
    ports:
    - "80:80"
    volumes:
    - ./docker-utils/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
    - web
    container_name: dcg_proxy

  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    volumes:
      - ./data-redis:/data
    restart: always  
    container_name: dcg_redis

volumes:
  db-data: {}
